# Generated by Django 5.2.7 on 2025-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beverage_photos/')),
                ('type', models.CharField(choices=[('coffee', 'Кофе'), ('new_drinks', 'Новые напитки'), ('iced_coffee', 'Холодный кофе'), ('cold_drinks', 'Холодные напитки'), ('decaf', 'Без кофеина'), ('fresh_juices', 'Свежие соки'), ('tea', 'Чай'), ('not_coffee', 'Не кофе')], default='coffee', max_length=40)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ingredients', models.TextField(blank=True)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='menu_photos/')),
                ('type', models.CharField(choices=[('new', 'Новинки'), ('breakfast', 'Завтрак'), ('omelette', 'Омлеты'), ('crepes_quiches', 'Блины и киши'), ('sweet_crepes', 'Сладкие блины'), ('soups', 'Супы'), ('salads', 'Салаты'), ('sandwiches', 'Сэндвичи и тосты'), ('main_courses', 'Основные блюда'), ('other', 'Другое')], default='other', max_length=40)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
    ]
