# Generated by Django 5.2.7 on 2025-11-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beverage',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['type']},
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.CreateModel(
            name='BeverageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('uz', 'Uzbek')], max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menu.beverage')),
            ],
            options={
                'unique_together': {('beverage', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('uz', 'Uzbek')], max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('ingredients', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menu.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'language')},
            },
        ),
    ]
