"""
Django settings for BonCafe project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-(itv*6*$eer@r-^6&50fy7#9^)sy^)-n=2_))zi5*50i2yqbt(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') in ('1', 'true', 'True')

# ALLOWED_HOSTS: set DJANGO_ALLOWED_HOSTS as comma separated list in Vercel.
allowed = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if allowed:
    ALLOWED_HOSTS = [h.strip() for h in allowed.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = []

# If running in production (DEBUG False) ensure a real SECRET_KEY was provided.
if not DEBUG and (not SECRET_KEY or SECRET_KEY.startswith('django-insecure-')):
    raise RuntimeError('DJANGO_SECRET_KEY must be set in production environment')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "parler",
    "apps.menu",
    "apps.branches",
    "django.contrib.sites",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise allows serving static files directly from the Python app (useful on Vercel)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',]

CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = 'BonCafe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Use a string path for the templates dir to avoid static-analysis warnings
        'DIRS': [str(BASE_DIR / 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BonCafe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Languages supported by the application
LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
    ('uz', 'Uzbek'),
]

# Parler configuration
PARLER_LANGUAGES = {
    None: (
        {'code': 'ru'},  # Russian as default
        {'code': 'en'},  # English
        {'code': 'uz'},  # Uzbek
    ),
    'default': {
        'fallbacks': ['ru'],          # Russian as fallback
        'hide_untranslated': False,   # Show untranslated content
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Directory where `collectstatic` will place static files for serving
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use WhiteNoise storage backend to compress files and add headers
# CompressedManifestStaticFilesStorage may raise errors if you don't run collectstatic
# so we use CompressedStaticFilesStorage which is simpler and safer for builds.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# SITE URL - used for callback building
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")

# When running behind a proxy (Vercel), detect secure requests
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF trusted origins: prefer explicit env var, otherwise derive from SITE_URL
csrf_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS')
if csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_origins.split(',') if o.strip()]
else:
    # derive https origin from SITE_URL when possible
    if SITE_URL.startswith('http'):
        CSRF_TRUSTED_ORIGINS = [SITE_URL.rstrip('/')]
    else:
        CSRF_TRUSTED_ORIGINS = []


# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
}

# Click config (use env vars in production)
# CLICK = {
#     "MERCHANT_ID": os.environ.get("CLICK_MERCHANT_ID", "<your_test_merchant_id>"),
#     "SERVICE_ID": os.environ.get("CLICK_SERVICE_ID", "<your_test_service_id>"),
#     "MERCHANT_USER_ID": os.environ.get("CLICK_MERCHANT_USER_ID", "<merchant_user_id>"),
#     "SECRET_KEY": os.environ.get("CLICK_SECRET_KEY", "<secret_key>"),
#     "API_BASE": os.environ.get("CLICK_API_BASE", "https://api.click.uz"),
#     "TEST_MODE": os.environ.get("CLICK_TEST_MODE", "1") in ("1", "true", "True"),
# }


SITE_ID = 1