# Generated by Django 5.2.7 on 2025-10-30 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='branch_photos/')),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Customer's phone number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('customer_name', models.CharField(blank=True, help_text='Optional customer name', max_length=100)),
                ('stars', models.PositiveSmallIntegerField(choices=[(0, '0 Stars'), (1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0, help_text='Rating from 0 to 5 stars')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('phone_number', 'branch')},
            },
        ),
    ]
