# Generated by Django 5.2.7 on 2025-11-03 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email (optional for web reviews)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('web', 'Website Form'), ('phone', 'Phone Call'), ('admin', 'Admin Panel')], default='web', help_text='How the review was submitted', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_name',
            field=models.CharField(help_text='Customer name (required for web reviews)', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(help_text='Review message/feedback'),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Customer's phone number (for phone-based reviews)", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1, help_text='Rating from 1 to 5 stars'),
        ),
    ]
